# Generated by Django 4.0.4 on 2022-05-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allAccounts', '0004_user_is_accounts_manager_user_is_cinema_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_accounts_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_cinema_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_clubRep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
