# Generated by Django 4.0.4 on 2022-05-09 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('postCode', models.CharField(max_length=10)),
                ('house_num', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('phone_num', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('clubID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('actor1', models.CharField(blank=True, max_length=100, null=True)),
                ('actor2', models.CharField(blank=True, max_length=100, null=True)),
                ('actor3', models.CharField(blank=True, max_length=100, null=True)),
                ('ageRating', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('uniqueId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, choices=[('screen1', 'Screen1'), ('screen2', 'Screen2'), ('screen3', 'Screen3'), ('screen4', 'Screen4'), ('screen5', 'Screen5')], max_length=50, null=True)),
                ('tickets', models.IntegerField(default=300, max_length=300)),
                ('ticketPrice', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UWE.movies')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubRepFirstName', models.CharField(max_length=50)),
                ('clubRepLastName', models.CharField(max_length=50)),
                ('club_rep_number', models.CharField(blank=True, default=uuid.UUID('f90dd27b-cb86-4cc7-a75a-b922ef9b5747'), max_length=1300, null=True, unique=True)),
                ('club_rep_email', models.EmailField(max_length=100, null=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UWE.club')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_uniqueID', models.CharField(blank=True, default=uuid.UUID('913218d4-c875-4972-8628-79032117bda0'), max_length=100, null=True, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.BigIntegerField()),
                ('Age', models.IntegerField()),
                ('Seats_quantity', models.IntegerField(blank=True, max_length=100, null=True)),
                ('Showing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UWE.screen')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UWE.movies')),
            ],
        ),
    ]
