# Generated by Django 4.0.4 on 2022-05-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Credits', 'Credits')], default='Credits', max_length=11)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('postCode', models.CharField(max_length=10)),
                ('house_num', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('clubID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubRepFirstName', models.CharField(max_length=50)),
                ('clubRepLastName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('club_rep_number', models.CharField(max_length=11)),
                ('club_rep_email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticketPrice', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('actor1', models.CharField(blank=True, max_length=100, null=True)),
                ('actor2', models.CharField(blank=True, max_length=100, null=True)),
                ('actor3', models.CharField(blank=True, max_length=100, null=True)),
                ('ageRating', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenShowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, choices=[('screen1', 'Screen1'), ('screen2', 'Screen2'), ('screen3', 'Screen3'), ('screen4', 'Screen4'), ('screen5', 'Screen5')], max_length=50, null=True)),
                ('tickets', models.IntegerField(default=0, max_length=300)),
                ('times', models.CharField(blank=True, choices=[('11:10', 'Time1'), ('12:15', 'Time2'), ('15:30', 'Time3'), ('17:15', 'Time4'), ('18:00', 'Time5'), ('17:45', 'Time6')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seatsAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('', 'Select'), ('Regular', 'Regular'), ('V.I.P', 'V.I.P')], max_length=8)),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(default=False)),
                ('sale_price', models.IntegerField(default=False)),
                ('new_price', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(max_length=300)),
                ('price', models.IntegerField()),
                ('movie', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='UWE.movies')),
            ],
        ),
    ]
