# Generated by Django 4.0.4 on 2022-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
