# Generated by Django 4.0.4 on 2022-05-09 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('3d0b2e97-742e-46b5-a870-cfc9f0e66296'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('2b2d436d-fd36-42a0-bccc-8c6c1eeb10e2'), max_length=1300, null=True, unique=True),
        ),
    ]
