# Generated by Django 4.0.4 on 2022-05-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshowing',
            old_name='times',
            new_name='Showings',
        ),
    ]
