# Generated by Django 4.0.4 on 2022-05-09 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0003_alter_booking_booking_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('360b2980-be0d-41d9-87d9-171d19a4ca5c'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('c8d0086e-ca8f-4512-bf9f-f82363cae06b'), max_length=1300, null=True, unique=True),
        ),
    ]
