# Generated by Django 4.0.4 on 2022-05-09 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0004_alter_booking_booking_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('e24c40c9-5008-4c72-a071-66b19ce0816a'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('587ed471-aed5-41ed-a779-f0bb15a023dd'), max_length=1300, null=True, unique=True),
        ),
    ]
