# Generated by Django 4.0.4 on 2022-05-05 12:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0004_bookingreservation_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('age', models.IntegerField()),
                ('screen', models.CharField(blank=True, choices=[('screen1', 'Screen1'), ('screen2', 'Screen2'), ('screen3', 'Screen3'), ('screen4', 'Screen4'), ('screen5', 'Screen5')], max_length=50, null=True)),
                ('seats', models.CharField(blank=True, max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWE.movies')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, choices=[('screen1', 'Screen1'), ('screen2', 'Screen2'), ('screen3', 'Screen3'), ('screen4', 'Screen4'), ('screen5', 'Screen5')], max_length=50, null=True)),
                ('tickets', models.IntegerField(default=300, max_length=300)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UWE.movies')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingreservation',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='screenshowing',
            name='movie',
        ),
        migrations.DeleteModel(
            name='seatsAvailable',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='TicketDiscount',
        ),
        migrations.AlterField(
            model_name='club',
            name='phone_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 0, 0)),
        ),
        migrations.DeleteModel(
            name='bookingReservation',
        ),
        migrations.DeleteModel(
            name='ScreenShowing',
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
