# Generated by Django 4.0.4 on 2022-05-09 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0005_alter_booking_booking_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('37f638df-33d2-4dd2-badc-40757565e4e5'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('3b0497c6-b569-4aa5-b26e-3446059edc25'), max_length=1300, null=True, unique=True),
        ),
    ]
