# Generated by Django 4.0.4 on 2022-05-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0006_remove_booking_movie_remove_booking_screen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='mobile',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='seats',
            new_name='Seats_quantity',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='showing',
            new_name='Showing',
        ),
    ]
