# Generated by Django 4.0.4 on 2022-05-09 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0006_alter_booking_booking_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('a9becfcb-588b-4c2f-b3a0-893cd12f03bd'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('a787d9f7-6200-4ec7-997a-d898ef55f290'), max_length=1300, null=True, unique=True),
        ),
    ]
