# Generated by Django 4.0.4 on 2022-05-09 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0007_alter_booking_booking_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('166f540c-6528-4271-aaf8-94baf304748e'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('911521f6-651f-4e17-bebe-98865413a507'), max_length=1300, null=True, unique=True),
        ),
    ]
