# Generated by Django 4.0.4 on 2022-05-09 13:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0008_alter_booking_booking_uniqueid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrep',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_uniqueID',
            field=models.CharField(blank=True, default=uuid.UUID('dfbd47a2-dee7-4418-a0b3-65473eb8f89f'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('30a30a1d-4ea3-4d80-b211-0ecc5fc2cf84'), max_length=1300, null=True, unique=True),
        ),
    ]
