# Generated by Django 4.0.4 on 2022-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0008_booking_movie_screen_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='ticketPrice',
        ),
        migrations.AddField(
            model_name='screen',
            name='ticketPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
