# Generated by Django 4.0.4 on 2022-05-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0009_remove_movies_ticketprice_screen_ticketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Phone_Number',
            field=models.BigIntegerField(),
        ),
    ]
