# Generated by Django 4.0.4 on 2022-05-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0010_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
