# Generated by Django 4.0.4 on 2022-05-09 11:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWE', '0012_alter_clubrep_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 5, 4, 0, 0)),
        ),
    ]
