# Generated by Django 4.0.4 on 2022-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0013_booking_user_alter_clubrep_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Seats_quantity',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
