# Generated by Django 4.0.4 on 2022-05-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0014_alter_movies_dateandtime_alter_movies_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='dateAndTime',
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
