# Generated by Django 4.0.4 on 2022-05-09 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UWE', '0014_alter_booking_seats_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, default=uuid.UUID('6188327c-9efa-4c1d-b529-91f758c9c5f9'), max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clubrep',
            name='club_rep_number',
            field=models.CharField(blank=True, default=uuid.UUID('14eacaa4-7066-4b9c-96ad-cd66761a9789'), max_length=100, null=True, unique=True),
        ),
    ]
